name: Delete old players daily

on:
  schedule:
    - cron: '0 0 * * *' 

jobs:
  delete-old-players:
    runs-on: ubuntu-latest

    steps:
      - name: Call Supabase RPC to delete old players
        uses: actions/http-client@v2
        with:
          url: ${{ secrets.SUPABASE_URL }}/rest/v1/rpc/delete_old_players
          method: POST
          headers: |
            apikey: ${{ secrets.SUPABASE_ANON_KEY }}
            Authorization: Bearer ${{ secrets.SUPABASE_SERVICE_ROLE_KEY }}
            Content-Type: application/json
