name: Delete old players weekly

on:
  schedule:
    - cron: '0 0 * * 0' # Roda todo domingo à meia-noite UTC

jobs:
  delete-old-players:
    runs-on: ubuntu-latest
    steps:
      - name: Call Supabase RPC to delete old players
        uses: fjogeleit/http-request-action@v1
        with:
          url: ${{ secrets.SUPABASE_URL }}/rest/v1/rpc/delete_old_players
          method: POST
          customHeaders: '{"apikey": "${{ secrets.SUPABASE_ANON_KEY }}", "Authorization": "Bearer ${{ secrets.SUPABASE_ANON_KEY }}", "Content-Type": "application/json"}'
          data: '{"days_threshold": 7}'
